Repository milieuinfo/webcomponent-vl-ui-wizard, pull requests merged in 2020-05, with the labels that each got.

#13 Lock file maintenance
  package-lock.json
Labels: chore, dependencies, renovate

#15 Lock file maintenance
  package-lock.json
Labels: chore, dependencies, renovate

#22 Update dependency vl-ui-util to v5.1.9
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#24 Build min variant maakt nu gebruik van min dependency varianten
  .mocharc.js
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  src/style.css
  src/style.css.map
Labels: bug

#23 Niet automatisch titel tabindex toevoegen
  src/vl-wizard-pane.js
  test/unit/vl-wizard-pane.test.html
Labels: bug

#32 Introductie activated event wanneer vl-wizard-pane actief wordt
  dist/vl-wizard-pane.js
  dist/vl-wizard-pane.src.js
  src/vl-wizard-pane.js
  test/e2e/wizard.test.js
  test/unit/vl-wizard-pane.test.html
Labels: enhancement

#29 Lock file maintenance
  package-lock.json
Labels: chore, dependencies, renovate

#38 De enablePreviousPane/enableNextPane functie mag alleen de navigatie naar de vorige/volgende pane activeren
  CODEOWNERS
  package-lock.json
  src/vl-wizard.js
  test/e2e/components/vl-wizard.js
  test/e2e/pages/vl-wizard.page.js
  test/e2e/wizard.test.js
  test/unit/vl-wizard.test.html
Labels: bug
