Repository milieuinfo/webcomponent-vl-ui-wizard, pull requests merged in 2020-07, with the labels that each got.

#56 Update dependency @govflanders/vl-ui-util to v3.10.1
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#57 Update dependencies
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  src/style.scss
  src/vl-wizard-pane.js
  test/e2e/wizard.test.js
Labels: chore

#58 Stijl verbetering wanneer niet gecombineerd met niet relative parent elementen
  dist/vl-wizard.js
  dist/vl-wizard.min.js
  dist/vl-wizard.src.js
  src/vl-wizard.js
Labels: bug

#59 Introductie disabled progress-bar-step cursor stijl
  dist/vl-wizard.js
  dist/vl-wizard.min.js
  dist/vl-wizard.src.js
  package-lock.json
  package.json
  src/vl-wizard.js
  test/unit/vl-wizard.test.html
Labels: bug
