Repository milieuinfo/webcomponent-vl-ui-wizard, pull requests merged in 2020-04, with the labels that each got.

#4 Update dependency vl-ui-util to v5.1.5
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#7 Update vl-ui-progress-bar
  package-lock.json
  package.json
Labels: bug

#9 Update util
  package.json
Labels: chore

#10 Update dependency @govflanders/vl-ui-util to v3.9.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#12 Update dependency vl-ui-util to v5.1.7
  package-lock.json
  package.json
Labels: chore, dependencies, renovate
