Repository milieuinfo/webcomponent-vl-ui-wizard, pull requests merged in 2020-06, with the labels that each got.

#40 Introductie vl-ui-demo en ESlint
  .eslintrc.json
  demo/demo.css
  demo/demo.css.map
  demo/demo.js
  demo/vl-wizard.html
  index.js
  package-lock.json
  package.json
  src/index.js
  src/vl-wizard-all.js
  src/vl-wizard-pane.js
  src/vl-wizard.js
  test/e2e/components/vl-wizard-pane.js
  test/e2e/components/vl-wizard.js
  test/e2e/pages/vl-wizard.page.js
  test/e2e/wizard.test.js
  test/unit/vl-wizard-pane.test.html
  test/unit/vl-wizard.test.html
Labels: chore

#42 Voeg header.remove en footer.remove toe aan load-functie
  .vscode/launch.json
  package-lock.json
  package.json
  test/e2e/pages/vl-wizard.page.js
  test/unit/vl-wizard-pane.test.html
  test/unit/vl-wizard.test.html
Labels: bugfix

#45 Introductie nieuw Vlaanderen icon font
  package-lock.json
  package.json
  src/style.css
  test/e2e/pages/vl-wizard.page.js
Labels: bug

#48 Resize event activeert niet meer het versturen van een activated event
  dist/vl-wizard-pane.js
  dist/vl-wizard-pane.min.js
  dist/vl-wizard-pane.src.js
  src/vl-wizard-pane.js
  test/unit/vl-wizard-pane.test.html
Labels: bug

#50 Attributen op vl-wizard niveau ook toepassen op dynamisch toegevoegde vl-wizard-pane elementen
  dist/vl-wizard-all.min.js
  dist/vl-wizard-pane.js
  dist/vl-wizard-pane.min.js
  dist/vl-wizard-pane.src.js
  dist/vl-wizard.js
  dist/vl-wizard.min.js
  dist/vl-wizard.src.js
  package-lock.json
  package.json
  src/vl-wizard-pane.js
  src/vl-wizard.js
  test/docker-compose.yml
  test/unit/vl-wizard-pane.test.html
  test/unit/vl-wizard.test.html
Labels: enhancement

#51 Deduplicatie NPM run scripts
  bamboo-specs/bamboo.yml
  package-lock.json
  package.json
  test/docker-compose.yml
Labels: chore

#52 #11: fix timing in testen
  test/unit/vl-wizard.test.html
Labels: chore

#54 Oplossing voor probleem dat meerdere panes door elkaar gevisualiseerd worden
  dist/vl-wizard-pane.js
  dist/vl-wizard-pane.min.js
  dist/vl-wizard-pane.src.js
  lib/wizard.js
  src/vl-wizard-pane.js
Labels: bug
